version: '3.8'
name: repo

volumes:
    database:
        driver: local

networks:
    repo:
        driver: bridge

services:
    postgres:
        image: postgres:latest
        restart: always
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        networks:
            - repo
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
    rcli:
        image: redis:latest
        links:
            - redis
        command: redis-cli -h redis
