version: '3.8'
name: lms

volumes:
    database:
        driver: local

networks:
    lms:
        driver: bridge

services:
    postgres:
        image: postgres:latest
        restart: always
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lms
        ports:
            - 5432:5432
        networks:
            - lms
